# Show available tasks
default:
    @just --list

# Plain HTTP on a LAN address is not a secure context (no gamepads, no
# WebGPU); from another machine, prefer an SSH tunnel to localhost (AGENTS.md).
# Run the frontend locally (requires trunk); `just dev 0.0.0.0` serves the LAN
dev address="127.0.0.1":
    @trunk serve --address {{address}}

# Release build (same as CI; public URL defaults to /ditoditoinfinito/)
build public_url="/ditoditoinfinito/":
    @trunk build --release --public-url "{{public_url}}"

# Check the web app for wasm32
app-check:
    @cargo check -p ditoditoinfinito --target wasm32-unknown-unknown

# Check the platform-independent crates natively
core-check:
    @cargo check -p ddi-chart -p ddi-engine -p ddi-render -p ddi-platform -p ddi-library -p xtask

# Run all checks
check: core-check app-check regen-seo reuse-lint

# Run native unit tests
test:
    @cargo test -p ddi-chart -p ddi-engine -p ddi-render -p ddi-platform -p ddi-library -p xtask --features ddi-platform/decode

# Regenerate the SEO fragments and sitemap from seo/metadata.toml
# (trunk also runs this automatically as a pre_build hook)
regen-seo:
    @cargo run -p xtask -- regen-seo

# Verify REUSE/SPDX licensing metadata (REUSE.toml + LICENSES/)
reuse-lint:
    @uvx --from 'reuse[charset-normalizer]' reuse lint

fmt:
    cargo fmt --all

# Update Rust lockfile to latest versions allowed by manifests
update-cargo:
    @cargo update -v

# Clean local artifacts generated by dev workflows
clean:
    @rm -rf dist .trunk target
