[package]
name = "ddi-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "DitoDitoInfinito: deterministic gameplay core"

[dependencies]
ddi-chart.workspace = true
ddi-platform.workspace = true
serde.workspace = true
