//! Credits screen: renders `credits/credits.json` (generated by
//! `xtask gen-credits`), which carries the attribution the asset licences
//! require.

use serde::Deserialize;
use yew::prelude::*;

use crate::songs::fetch_text;

#[derive(Clone, Debug, PartialEq, Deserialize)]
struct Credits {
    songs: Vec<SongCredit>,
    fonts: Vec<FontCredit>,
}

#[derive(Clone, Debug, PartialEq, Deserialize)]
struct SongCredit {
    title: String,
    artist: String,
    source_url: String,
    source_path: String,
    source_commit: String,
    #[serde(default)]
    retrieved: String,
    parts: Vec<PartCredit>,
    #[serde(default)]
    chart_authors: std::collections::BTreeMap<String, Vec<String>>,
    #[serde(default)]
    excluded: Vec<String>,
    #[serde(default)]
    modifications: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Deserialize)]
struct PartCredit {
    part: String,
    spdx: String,
    holders: Vec<String>,
    url: String,
}

#[derive(Clone, Debug, PartialEq, Deserialize)]
struct FontCredit {
    file: String,
    spdx: String,
    holders: String,
    source: String,
    #[serde(default)]
    modified: String,
}

pub(crate) struct Msg(Result<Credits, String>);

pub(crate) struct CreditsScreen {
    state: Option<Result<Credits, String>>,
}

impl Component for CreditsScreen {
    type Message = Msg;
    type Properties = ();

    fn create(ctx: &Context<Self>) -> Self {
        ctx.link().send_future(async {
            let r = match fetch_text("credits/credits.json").await {
                Ok(t) => serde_json::from_str::<Credits>(&t).map_err(|e| e.to_string()),
                Err(e) => Err(e),
            };
            Msg(r)
        });
        CreditsScreen { state: None }
    }

    fn update(&mut self, _ctx: &Context<Self>, msg: Self::Message) -> bool {
        self.state = Some(msg.0);
        true
    }

    fn view(&self, _ctx: &Context<Self>) -> Html {
        let body = match &self.state {
            None => html! { <p class="muted">{ "loading…" }</p> },
            Some(Err(e)) => html! { <p class="error">{ e }</p> },
            Some(Ok(c)) => html! {
                <>
                    <p>{ "Dito Dito Infinito's code is MIT-licensed. The bundled demo songs and fonts are third-party works used under their own licences, credited here as those licences require." }</p>
                    <h2>{ "Songs" }</h2>
                    { for c.songs.iter().map(song) }
                    <h2>{ "Fonts" }</h2>
                    <ul>
                        { for c.fonts.iter().map(|f| html! {
                            <li>
                                <code>{ &f.file }</code>{ ": " }{ &f.holders }{ " — " }{ &f.spdx }
                                { " · " }<a href={f.source.clone()}>{ "source" }</a>
                                { if f.modified.is_empty() { html!{} } else { html!{ <span class="muted">{ format!(" · modified: {}", f.modified) }</span> } } }
                            </li>
                        }) }
                    </ul>
                </>
            },
        };
        html! {
            <main class="shell">
                <h1>{ "Credits" }</h1>
                { body }
            </main>
        }
    }
}

fn song(s: &SongCredit) -> Html {
    html! {
        <section class="credit-song">
            <h3>{ format!("{} — {}", s.title, s.artist) }</h3>
            <p class="muted">
                { "Source: " }<a href={s.source_url.clone()}>{ &s.source_url }</a>
                { format!(" (commit {}, folder “{}”{})", &s.source_commit[..s.source_commit.len().min(10)], s.source_path,
                    if s.retrieved.is_empty() { String::new() } else { format!(", retrieved {}", s.retrieved) }) }
            </p>
            <ul>
                { for s.parts.iter().map(|p| html! {
                    <li><strong>{ &p.part }</strong>{ ": " }{ p.holders.join(", ") }{ " — " }<a href={p.url.clone()}>{ &p.spdx }</a></li>
                }) }
                { if s.chart_authors.is_empty() { html!{} } else { html! {
                    <li>{ "chart authors: " }
                        { for s.chart_authors.iter().map(|(a, charts)| html!{ <span class="chart-author">{ a }{ " (" }{ charts.join(", ") }{ ") " }</span> }) }
                    </li>
                } } }
                { if s.excluded.is_empty() { html!{} } else { html!{ <li class="muted">{ "not included: " }{ s.excluded.join("; ") }</li> } } }
                <li class="muted">{ if s.modifications.is_empty() { "modifications: none".to_string() } else { format!("modifications: {}", s.modifications.join("; ")) } }</li>
            </ul>
        </section>
    }
}
