//! The song library: bundled songs, listed by a manifest at
//! `songs/index.json` (generated by `xtask gen-songs` from `assets/songs/`)
//! and served as static assets next to the app, plus songs the player
//! imported, kept in IndexedDB (see [`crate::import`]). Both kinds share the
//! manifest entry shape; imported entries name their files `chart.<ext>`,
//! `music.<ext>`, `banner.<ext>` and `background.<ext>`, stored as blobs
//! under `<id>/<file>`.

use std::collections::BTreeMap;

use ddi_chart::Song;
use ddi_chart::formats::sm::parse_simfile;
use ddi_library::backgrounds::BgImage;
use serde::{Deserialize, Serialize};
use wasm_bindgen::{JsCast, JsValue};
use web_sys::Blob;

use crate::web::files::{blob_bytes, object_url};
use crate::web::idb::{self, Db, Write};

pub(crate) use ddi_library::manifest::{Manifest, ManifestEntry};

fn base_url() -> String {
    // Assets live next to index.html; the document URL (minus hash/query)
    // points at the right directory under any `--public-url`.
    let href = web_sys::window()
        .and_then(|w| w.document())
        .and_then(|d| d.base_uri().ok().flatten())
        .unwrap_or_default();
    let href = href.split('#').next().unwrap_or("");
    let href = href.split('?').next().unwrap_or("");
    match href.rfind('/') {
        Some(i) => href[..=i].to_string(),
        None => String::new(),
    }
}

pub(crate) fn asset_url(path: &str) -> String {
    format!("{}{}", base_url(), path)
}

pub(crate) async fn fetch_text(path: &str) -> Result<String, String> {
    let resp = gloo::net::http::Request::get(&asset_url(path))
        .send()
        .await
        .map_err(|e| format!("GET {path}: {e}"))?;
    if !resp.ok() {
        return Err(format!("GET {path}: HTTP {}", resp.status()));
    }
    resp.text().await.map_err(|e| format!("GET {path}: {e}"))
}

pub(crate) async fn fetch_bytes(path: &str) -> Result<Vec<u8>, String> {
    let resp = gloo::net::http::Request::get(&asset_url(path))
        .send()
        .await
        .map_err(|e| format!("GET {path}: {e}"))?;
    if !resp.ok() {
        return Err(format!("GET {path}: HTTP {}", resp.status()));
    }
    resp.binary().await.map_err(|e| format!("GET {path}: {e}"))
}

pub(crate) async fn load_manifest() -> Result<Manifest, String> {
    let text = fetch_text("songs/index.json").await?;
    serde_json::from_str(&text).map_err(|e| format!("songs/index.json: {e}"))
}

/// An imported song as stored in IndexedDB (JSON under its id).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub(crate) struct ImportedSong {
    pub(crate) entry: ManifestEntry,
    /// Pack (group folder or zip name) the song came from.
    pub(crate) pack: String,
    /// Path of the song folder inside what was imported.
    #[serde(default)]
    pub(crate) dir: String,
    /// ms since epoch.
    #[serde(default)]
    pub(crate) imported: f64,
    /// Total stored bytes.
    #[serde(default)]
    pub(crate) bytes: f64,
    /// Storage key of the kept folder it was imported from (Chromium),
    /// which can re-read it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) folder: Option<String>,
    /// Files left in that folder instead of copied, by the name the entry
    /// uses (`music.ogg`, `background.png`, `bg/<path>`).
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub(crate) links: BTreeMap<String, Link>,
    /// Storage key of the Dancing☆Onigiri work the song belongs to, stored
    /// once for all its songs.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) work: Option<String>,
}

/// Where a song's files live.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) enum Origin {
    Bundled,
    /// From the library, imported with the pack of this name.
    Imported(String),
}

/// Every song the game can list.
#[derive(Default)]
pub(crate) struct Library {
    pub(crate) bundled: Vec<ManifestEntry>,
    /// Sorted by pack, then title.
    pub(crate) imported: Vec<ImportedSong>,
    /// Why the imported songs could not be read, if they could not (the
    /// bundled ones still work).
    pub(crate) imported_error: Option<String>,
    /// Ids of stored records that no longer parse (a format change, or a
    /// bug); listed so they can be removed.
    pub(crate) unreadable: Vec<String>,
}

impl Library {
    pub(crate) async fn load() -> Result<Library, String> {
        let bundled = load_manifest().await?.songs;
        let (imported, unreadable, imported_error) = match load_imported().await {
            Ok((songs, unreadable)) => (songs, unreadable, None),
            Err(e) => (Vec::new(), Vec::new(), Some(e)),
        };
        Ok(Library {
            bundled,
            imported,
            imported_error,
            unreadable,
        })
    }
}

/// Imported songs, and the ids of records that do not parse.
async fn load_imported() -> Result<(Vec<ImportedSong>, Vec<String>), String> {
    let db = Db::open().await?;
    let mut songs = Vec::new();
    let mut unreadable = Vec::new();
    for (id, value) in db.entries(idb::SONGS).await? {
        match value
            .as_string()
            .and_then(|json| serde_json::from_str::<ImportedSong>(&json).ok())
        {
            Some(song) => songs.push(song),
            None => unreadable.push(id),
        }
    }
    songs.sort_by(|a, b| {
        let key = |s: &ImportedSong| (s.pack.to_lowercase(), s.entry.title.to_lowercase());
        key(a).cmp(&key(b))
    });
    Ok((songs, unreadable))
}

/// Whether an id names an imported song (`ddi_library::pack::song_id`).
pub(crate) fn is_imported_id(id: &str) -> bool {
    id.starts_with("u-")
}

/// Object URLs for the banners of imported songs, read in one transaction.
/// Revoke them with [`crate::web::files::revoke_object_url`].
pub(crate) async fn imported_banner_urls(entries: &[ManifestEntry]) -> Vec<(String, String)> {
    let wanted: Vec<(&str, String)> = entries
        .iter()
        .filter_map(|e| Some((e.id.as_str(), file_key(&e.id, e.banner.as_ref()?))))
        .collect();
    let keys: Vec<String> = wanted.iter().map(|(_, k)| k.clone()).collect();
    let Ok(db) = Db::open().await else {
        return Vec::new();
    };
    let Ok(blobs) = db.get_many(idb::FILES, &keys).await else {
        return Vec::new();
    };
    wanted
        .iter()
        .zip(blobs)
        .filter_map(|((id, _), v)| {
            let blob = v?.dyn_into::<Blob>().ok()?;
            Some((id.to_string(), object_url(&blob)?))
        })
        .collect()
}

const FOLDER_PREFIX: &str = "folders/";

/// Keeps a picked folder's handle, so it can be re-read in place, and
/// returns its storage key: the key it already has when the same folder
/// was picked before, else a new one (two folders may share a name).
pub(crate) async fn keep_folder(handle: &JsValue) -> Result<String, String> {
    for (key, kept) in kept_folders().await {
        if crate::web::folders::same(&kept, handle).await {
            return Ok(key);
        }
    }
    let key = format!(
        "{FOLDER_PREFIX}{}~{:x}",
        crate::web::folders::name(handle).to_lowercase(),
        js_sys::Date::now() as u64
    );
    let db = Db::open().await?;
    db.write(vec![Write::Put {
        store: idb::FILES,
        key: key.clone(),
        value: handle.clone(),
    }])
    .await?;
    Ok(key)
}

/// The kept folder handles, by storage key.
pub(crate) async fn kept_folders() -> Vec<(String, JsValue)> {
    let Ok(db) = Db::open().await else {
        return Vec::new();
    };
    let Ok(keys) = db.keys_with_prefix(idb::FILES, FOLDER_PREFIX).await else {
        return Vec::new();
    };
    let Ok(values) = db.get_many(idb::FILES, &keys).await else {
        return Vec::new();
    };
    keys.into_iter()
        .zip(values)
        .filter_map(|(k, v)| Some((k, v?)))
        .collect()
}

/// Storage key of a pack's banner (packs are told apart ignoring case).
pub(crate) fn pack_art_key(pack: &str) -> String {
    format!("{PACK_ART_PREFIX}{}", pack.to_lowercase())
}

const PACK_ART_PREFIX: &str = "packs/";

/// Object URLs of the stored pack banners, by lowercased pack name.
pub(crate) async fn pack_art_urls(packs: &[String]) -> Vec<(String, String)> {
    let keys: Vec<String> = packs.iter().map(|p| pack_art_key(p)).collect();
    let Ok(db) = Db::open().await else {
        return Vec::new();
    };
    let Ok(blobs) = db.get_many(idb::FILES, &keys).await else {
        return Vec::new();
    };
    packs
        .iter()
        .zip(blobs)
        .filter_map(|(pack, v)| {
            let blob = v?.dyn_into::<Blob>().ok()?;
            Some((pack.to_lowercase(), object_url(&blob)?))
        })
        .collect()
}

/// A song's encoded audio, bundled or imported (for previews).
pub(crate) async fn load_music(entry: &ManifestEntry) -> Result<Vec<u8>, String> {
    if is_imported_id(&entry.id) {
        let db = Db::open().await?;
        let song = imported_record(&db, &entry.id).await?;
        let blob = song_file(&db, &song, &entry.music)
            .await
            .map_err(|e| e.message())?;
        blob_bytes(&blob).await
    } else {
        fetch_bytes(&format!("songs/{}/{}", entry.id, entry.music)).await
    }
}

/// Where a linked file of an imported song is: in its kept folder.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub(crate) struct Link {
    /// Path inside the folder, without the folder's own name.
    pub(crate) path: String,
    /// For a file inside a zip at `path`, the entry's name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) entry: Option<String>,
}

/// Why a song could not load.
#[derive(Clone, Debug)]
pub(crate) enum LoadError {
    Failed(String),
    /// Its files are in a kept folder the browser asks again before
    /// reading (after a restart): ask from a click ([`crate::web::folders::access`]).
    NeedsAccess {
        handle: JsValue,
        name: String,
    },
}

impl From<String> for LoadError {
    fn from(e: String) -> LoadError {
        LoadError::Failed(e)
    }
}

impl From<&str> for LoadError {
    fn from(e: &str) -> LoadError {
        LoadError::Failed(e.to_string())
    }
}

impl LoadError {
    pub(crate) fn message(&self) -> String {
        match self {
            LoadError::Failed(e) => e.clone(),
            LoadError::NeedsAccess { name, .. } => {
                format!("reading the folder “{name}” needs your permission")
            }
        }
    }
}

/// An imported song's stored record.
pub(crate) async fn imported_record(db: &Db, id: &str) -> Result<ImportedSong, String> {
    let json = db
        .get(idb::SONGS, id)
        .await?
        .and_then(|v| v.as_string())
        .ok_or_else(|| format!("unknown song `{id}`"))?;
    serde_json::from_str(&json).map_err(|e| format!("stored song `{id}`: {e}"))
}

/// One of an imported song's files: copied into the browser, or read from
/// its kept folder when linked.
pub(crate) async fn song_file(db: &Db, song: &ImportedSong, file: &str) -> Result<Blob, LoadError> {
    let Some(link) = song.links.get(file) else {
        return Ok(imported_blob(db, &song.entry.id, file).await?);
    };
    let key = song
        .folder
        .as_ref()
        .ok_or("the folder this song plays from is unknown; import it again")?;
    let handle = db
        .get(idb::FILES, key)
        .await?
        .ok_or("the folder this song plays from is no longer kept; import it again")?;
    let name = crate::web::folders::name(&handle);
    if !crate::web::folders::granted(&handle).await {
        return Err(LoadError::NeedsAccess { handle, name });
    }
    let found = crate::web::folders::file(&handle, &link.path)
        .await
        .ok_or_else(|| {
            format!(
                "{} is no longer in the folder “{name}”; re-read the folder or import the song again",
                link.path
            )
        })?;
    match &link.entry {
        None => Ok(found.into()),
        Some(entry) => Ok(crate::import::zip_entry_blob(&found, entry).await?),
    }
}

/// Key of an imported song's file in the `files` store.
pub(crate) fn file_key(id: &str, file: &str) -> String {
    format!("{id}/{file}")
}

async fn imported_blob(db: &Db, id: &str, file: &str) -> Result<Blob, String> {
    db.get(idb::FILES, &file_key(id, file))
        .await?
        .and_then(|v| v.dyn_into::<Blob>().ok())
        .ok_or_else(|| format!("{file} is missing from the stored song; import it again"))
}

/// Background-change images a song shows at most, its own and shared ones
/// together (each is decoded and kept on the GPU during play).
pub(crate) const MAX_BG_IMAGES: usize = 32;

/// Storage key of an image from a shared background folder
/// (`RandomMovies/…`, `SongMovies/…`), kept for the whole library.
pub(crate) fn shared_key(shared_path: &str) -> String {
    format!("{SHARED_PREFIX}{shared_path}")
}

const SHARED_PREFIX: &str = "shared/";

/// Paths of the shared background images in the library.
pub(crate) async fn shared_paths(db: &Db) -> Result<Vec<String>, String> {
    Ok(db
        .keys_with_prefix(idb::FILES, SHARED_PREFIX)
        .await?
        .into_iter()
        .filter_map(|k| k.strip_prefix(SHARED_PREFIX).map(str::to_string))
        .collect())
}

/// A background image file of the song (bundled or imported): its
/// background, or an image its background changes show (stored as
/// `bg/<path>` when imported, or found in a shared folder: `shared` maps
/// names to shared paths). `None` when the song has no background.
pub(crate) async fn load_background(
    entry: &ManifestEntry,
    what: &BgImage,
    shared: &[(String, String)],
) -> Result<Option<Blob>, String> {
    if let BgImage::File(name) = what
        && let Some((_, path)) = shared.iter().find(|(n, _)| n == name)
    {
        let db = Db::open().await?;
        return db
            .get(idb::FILES, &shared_key(path))
            .await?
            .and_then(|v| v.dyn_into::<Blob>().ok())
            .map(Some)
            .ok_or_else(|| format!("shared background {path} is no longer stored"));
    }
    let (stored, bundled) = match what {
        BgImage::Song => match entry.background.as_ref() {
            Some(file) => (file.clone(), file.clone()),
            None => return Ok(None),
        },
        BgImage::File(path) => (format!("bg/{path}"), path.clone()),
    };
    if is_imported_id(&entry.id) {
        let db = Db::open().await?;
        let song = imported_record(&db, &entry.id).await?;
        song_file(&db, &song, &stored)
            .await
            .map(Some)
            .map_err(|e| e.message())
    } else {
        let bytes = fetch_bytes(&format!("songs/{}/{}", entry.id, bundled)).await?;
        crate::web::files::bytes_blob(&bytes, "").map(Some)
    }
}

/// A song with its chart parsed and audio bytes still encoded.
pub(crate) struct LoadedSong {
    pub(crate) entry: ManifestEntry,
    pub(crate) song: Song,
    pub(crate) music_bytes: Vec<u8>,
    /// Background-change images found in the library's shared folders:
    /// `(name as the simfile writes it, shared path)`.
    pub(crate) shared_bg: Vec<(String, String)>,
}

/// Finds a song by id among bundled and imported songs and loads it.
pub(crate) async fn load_song(id: &str) -> Result<LoadedSong, LoadError> {
    // Bundled songs never wait on IndexedDB (which can be unavailable or
    // blocked by another tab).
    let mut record = None;
    let (entry, origin) = if is_imported_id(id) {
        let db = Db::open().await?;
        let song = imported_record(&db, id).await?;
        let found = (song.entry.clone(), Origin::Imported(song.pack.clone()));
        record = Some(song);
        found
    } else {
        let entry = load_manifest()
            .await?
            .songs
            .into_iter()
            .find(|e| e.id == id)
            .ok_or_else(|| format!("unknown song `{id}`"))?;
        (entry, Origin::Bundled)
    };
    let (chart_text, music_bytes) = match &origin {
        Origin::Bundled => {
            let chart_text = fetch_text(&format!("songs/{}/{}", entry.id, entry.chart)).await?;
            let music = fetch_bytes(&format!("songs/{}/{}", entry.id, entry.music)).await?;
            (chart_text, music)
        }
        Origin::Imported(_) => {
            let song = record.as_ref().ok_or("the stored song went missing")?;
            let db = Db::open().await?;
            let chart = blob_bytes(&song_file(&db, song, &entry.chart).await?).await?;
            let music = blob_bytes(&song_file(&db, song, &entry.music).await?).await?;
            // Stored chart bytes are already UTF-8 (decoded at import).
            (String::from_utf8_lossy(&chart).into_owned(), music)
        }
    };
    let ext = entry.chart.rsplit('.').next().unwrap_or("sm");
    let song = if ext == ddi_library::danoni::STORED_EXT {
        load_work_song(&chart_text).await
    } else {
        parse_simfile(&chart_text, ext).map_err(|e| e.to_string())
    }
    .map_err(|e| format!("{}: {e}", entry.chart))?;
    // Images the song's folder lacks may be in a shared folder imported
    // before or after it; looked up now so the order does not matter.
    let shared_bg = match &origin {
        Origin::Imported(pack) => {
            let db = Db::open().await?;
            let shared = shared_paths(&db).await.unwrap_or_default();
            let mut found =
                ddi_library::backgrounds::shared_images(&entry.bg_shared, pack, &shared);
            found.truncate(MAX_BG_IMAGES.saturating_sub(entry.bg_images.len()));
            found
        }
        Origin::Bundled => Vec::new(),
    };
    Ok(LoadedSong {
        entry,
        song,
        music_bytes,
        shared_bg,
    })
}

/// The song a stored Dancing☆Onigiri work file describes, with the work's
/// fields read from where they are stored once for all its songs.
async fn load_work_song(text: &str) -> Result<Song, String> {
    let stored = ddi_library::danoni::StoredWork::parse(text)?;
    let shared = match &stored.work {
        Some(key) => {
            let db = Db::open().await?;
            let blob = db
                .get(idb::FILES, key)
                .await?
                .and_then(|v| v.dyn_into::<Blob>().ok())
                .ok_or("the work is no longer stored; import it again")?;
            Some(String::from_utf8_lossy(&blob_bytes(&blob).await?).into_owned())
        }
        None => None,
    };
    stored.song(shared.as_deref())
}

#[derive(Deserialize)]
struct WorkRef {
    #[serde(default)]
    work: Option<String>,
    #[serde(default)]
    pack: String,
    #[serde(default)]
    folder: Option<String>,
}

/// Drops what imported songs share once nothing refers to it: stored
/// Dancing☆Onigiri works, pack banners and kept folder handles.
pub(crate) async fn drop_unused_shared(db: &Db) -> Result<(), String> {
    // Only the references are read, so a record that no longer parses as
    // a whole still keeps what it uses.
    let refs: Vec<WorkRef> = db
        .entries(idb::SONGS)
        .await?
        .into_iter()
        .filter_map(|(_, v)| v.as_string())
        .filter_map(|json| serde_json::from_str::<WorkRef>(&json).ok())
        .collect();
    let used: std::collections::HashSet<String> = refs
        .iter()
        .filter_map(|r| r.work.clone())
        .chain(refs.iter().map(|r| pack_art_key(&r.pack)))
        .chain(refs.iter().filter_map(|r| r.folder.clone()))
        .collect();
    let mut unused = Vec::new();
    for prefix in [
        ddi_library::danoni::SHARED_WORK_PREFIX,
        PACK_ART_PREFIX,
        FOLDER_PREFIX,
    ] {
        unused.extend(
            db.keys_with_prefix(idb::FILES, prefix)
                .await?
                .into_iter()
                .filter(|k| !used.contains(k))
                .map(|key| Write::Delete {
                    store: idb::FILES,
                    key,
                }),
        );
    }
    if unused.is_empty() {
        return Ok(());
    }
    db.write(unused).await
}

/// Removes every imported song and file.
pub(crate) async fn clear_imported() -> Result<(), String> {
    let db = Db::open().await?;
    db.write(vec![
        Write::Clear { store: idb::SONGS },
        Write::Clear { store: idb::FILES },
    ])
    .await
}

/// Removes imported songs and their files.
pub(crate) async fn delete_imported(ids: &[String]) -> Result<(), String> {
    let db = Db::open().await?;
    let writes = ids
        .iter()
        .flat_map(|id| {
            [
                Write::Delete {
                    store: idb::SONGS,
                    key: id.clone(),
                },
                Write::DeletePrefix {
                    store: idb::FILES,
                    prefix: file_key(id, ""),
                },
            ]
        })
        .collect();
    db.write(writes).await?;
    drop_unused_shared(&db).await
}
