//! The song library: bundled songs, listed by a manifest at
//! `songs/index.json` (generated by `xtask gen-songs` from `assets/songs/`)
//! and served as static assets next to the app, plus songs the player
//! imported, kept in IndexedDB (see [`crate::import`]). Both kinds share the
//! manifest entry shape; imported entries name their files `chart.<ext>`,
//! `music.<ext>`, `banner.<ext>` and `background.<ext>`, stored as blobs
//! under `<id>/<file>`.

use ddi_chart::Song;
use ddi_chart::formats::sm::parse_simfile;
use serde::{Deserialize, Serialize};
use wasm_bindgen::JsCast;
use web_sys::Blob;

use crate::web::files::{blob_bytes, object_url};
use crate::web::idb::{self, Db, Write};

pub(crate) use ddi_library::manifest::{Manifest, ManifestEntry};

fn base_url() -> String {
    // Assets live next to index.html; the document URL (minus hash/query)
    // points at the right directory under any `--public-url`.
    let href = web_sys::window()
        .and_then(|w| w.document())
        .and_then(|d| d.base_uri().ok().flatten())
        .unwrap_or_default();
    let href = href.split('#').next().unwrap_or("");
    let href = href.split('?').next().unwrap_or("");
    match href.rfind('/') {
        Some(i) => href[..=i].to_string(),
        None => String::new(),
    }
}

pub(crate) fn asset_url(path: &str) -> String {
    format!("{}{}", base_url(), path)
}

pub(crate) async fn fetch_text(path: &str) -> Result<String, String> {
    let resp = gloo::net::http::Request::get(&asset_url(path))
        .send()
        .await
        .map_err(|e| format!("GET {path}: {e}"))?;
    if !resp.ok() {
        return Err(format!("GET {path}: HTTP {}", resp.status()));
    }
    resp.text().await.map_err(|e| format!("GET {path}: {e}"))
}

pub(crate) async fn fetch_bytes(path: &str) -> Result<Vec<u8>, String> {
    let resp = gloo::net::http::Request::get(&asset_url(path))
        .send()
        .await
        .map_err(|e| format!("GET {path}: {e}"))?;
    if !resp.ok() {
        return Err(format!("GET {path}: HTTP {}", resp.status()));
    }
    resp.binary().await.map_err(|e| format!("GET {path}: {e}"))
}

pub(crate) async fn load_manifest() -> Result<Manifest, String> {
    let text = fetch_text("songs/index.json").await?;
    serde_json::from_str(&text).map_err(|e| format!("songs/index.json: {e}"))
}

/// An imported song as stored in IndexedDB (JSON under its id).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub(crate) struct ImportedSong {
    pub(crate) entry: ManifestEntry,
    /// Pack (group folder or zip name) the song came from.
    pub(crate) pack: String,
    /// Path of the song folder inside what was imported.
    #[serde(default)]
    pub(crate) dir: String,
    /// ms since epoch.
    #[serde(default)]
    pub(crate) imported: f64,
    /// Total stored bytes.
    #[serde(default)]
    pub(crate) bytes: f64,
}

/// Where a song's files live.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Origin {
    Bundled,
    Imported,
}

/// Every song the game can list.
#[derive(Default)]
pub(crate) struct Library {
    pub(crate) bundled: Vec<ManifestEntry>,
    /// Sorted by pack, then title.
    pub(crate) imported: Vec<ImportedSong>,
    /// Why the imported songs could not be read, if they could not (the
    /// bundled ones still work).
    pub(crate) imported_error: Option<String>,
    /// Ids of stored records that no longer parse (a format change, or a
    /// bug); listed so they can be removed.
    pub(crate) unreadable: Vec<String>,
}

impl Library {
    pub(crate) async fn load() -> Result<Library, String> {
        let bundled = load_manifest().await?.songs;
        let (imported, unreadable, imported_error) = match load_imported().await {
            Ok((songs, unreadable)) => (songs, unreadable, None),
            Err(e) => (Vec::new(), Vec::new(), Some(e)),
        };
        Ok(Library {
            bundled,
            imported,
            imported_error,
            unreadable,
        })
    }
}

/// Imported songs, and the ids of records that do not parse.
async fn load_imported() -> Result<(Vec<ImportedSong>, Vec<String>), String> {
    let db = Db::open().await?;
    let mut songs = Vec::new();
    let mut unreadable = Vec::new();
    for (id, value) in db.entries(idb::SONGS).await? {
        match value
            .as_string()
            .and_then(|json| serde_json::from_str::<ImportedSong>(&json).ok())
        {
            Some(song) => songs.push(song),
            None => unreadable.push(id),
        }
    }
    songs.sort_by(|a, b| {
        let key = |s: &ImportedSong| (s.pack.to_lowercase(), s.entry.title.to_lowercase());
        key(a).cmp(&key(b))
    });
    Ok((songs, unreadable))
}

/// Whether an id names an imported song (`ddi_library::pack::song_id`).
pub(crate) fn is_imported_id(id: &str) -> bool {
    id.starts_with("u-")
}

/// Object URLs for the banners of imported songs, read in one transaction.
/// Revoke them with [`crate::web::files::revoke_object_url`].
pub(crate) async fn imported_banner_urls(entries: &[ManifestEntry]) -> Vec<(String, String)> {
    let wanted: Vec<(&str, String)> = entries
        .iter()
        .filter_map(|e| Some((e.id.as_str(), file_key(&e.id, e.banner.as_ref()?))))
        .collect();
    let keys: Vec<String> = wanted.iter().map(|(_, k)| k.clone()).collect();
    let Ok(db) = Db::open().await else {
        return Vec::new();
    };
    let Ok(blobs) = db.get_many(idb::FILES, &keys).await else {
        return Vec::new();
    };
    wanted
        .iter()
        .zip(blobs)
        .filter_map(|((id, _), v)| {
            let blob = v?.dyn_into::<Blob>().ok()?;
            Some((id.to_string(), object_url(&blob)?))
        })
        .collect()
}

/// A song's encoded audio, bundled or imported (for previews).
pub(crate) async fn load_music(entry: &ManifestEntry) -> Result<Vec<u8>, String> {
    if is_imported_id(&entry.id) {
        let db = Db::open().await?;
        blob_bytes(&imported_blob(&db, &entry.id, &entry.music).await?).await
    } else {
        fetch_bytes(&format!("songs/{}/{}", entry.id, entry.music)).await
    }
}

/// Key of an imported song's file in the `files` store.
pub(crate) fn file_key(id: &str, file: &str) -> String {
    format!("{id}/{file}")
}

async fn imported_blob(db: &Db, id: &str, file: &str) -> Result<Blob, String> {
    db.get(idb::FILES, &file_key(id, file))
        .await?
        .and_then(|v| v.dyn_into::<Blob>().ok())
        .ok_or_else(|| format!("{file} is missing from the stored song; import it again"))
}

/// The song's background image file, if it has one (bundled or imported).
pub(crate) async fn load_background(entry: &ManifestEntry) -> Result<Option<Blob>, String> {
    let Some(file) = entry.background.as_ref() else {
        return Ok(None);
    };
    if is_imported_id(&entry.id) {
        let db = Db::open().await?;
        imported_blob(&db, &entry.id, file).await.map(Some)
    } else {
        let bytes = fetch_bytes(&format!("songs/{}/{}", entry.id, file)).await?;
        crate::web::files::bytes_blob(&bytes, "").map(Some)
    }
}

/// A song with its chart parsed and audio bytes still encoded.
pub(crate) struct LoadedSong {
    pub(crate) entry: ManifestEntry,
    pub(crate) song: Song,
    pub(crate) music_bytes: Vec<u8>,
}

/// Finds a song by id among bundled and imported songs and loads it.
pub(crate) async fn load_song(id: &str) -> Result<LoadedSong, String> {
    // Bundled songs never wait on IndexedDB (which can be unavailable or
    // blocked by another tab).
    let (entry, origin) = if is_imported_id(id) {
        let db = Db::open().await?;
        let json = db
            .get(idb::SONGS, id)
            .await?
            .and_then(|v| v.as_string())
            .ok_or_else(|| format!("unknown song `{id}`"))?;
        let song: ImportedSong =
            serde_json::from_str(&json).map_err(|e| format!("stored song `{id}`: {e}"))?;
        (song.entry, Origin::Imported)
    } else {
        let entry = load_manifest()
            .await?
            .songs
            .into_iter()
            .find(|e| e.id == id)
            .ok_or_else(|| format!("unknown song `{id}`"))?;
        (entry, Origin::Bundled)
    };
    let (chart_text, music_bytes) = match origin {
        Origin::Bundled => {
            let chart_text = fetch_text(&format!("songs/{}/{}", entry.id, entry.chart)).await?;
            let music = fetch_bytes(&format!("songs/{}/{}", entry.id, entry.music)).await?;
            (chart_text, music)
        }
        Origin::Imported => {
            let db = Db::open().await?;
            let chart = blob_bytes(&imported_blob(&db, &entry.id, &entry.chart).await?).await?;
            let music = blob_bytes(&imported_blob(&db, &entry.id, &entry.music).await?).await?;
            // Stored chart bytes are already UTF-8 (decoded at import).
            (String::from_utf8_lossy(&chart).into_owned(), music)
        }
    };
    let ext = entry.chart.rsplit('.').next().unwrap_or("sm");
    let song = parse_simfile(&chart_text, ext).map_err(|e| format!("{}: {e}", entry.chart))?;
    Ok(LoadedSong {
        entry,
        song,
        music_bytes,
    })
}

/// Removes every imported song and file.
pub(crate) async fn clear_imported() -> Result<(), String> {
    let db = Db::open().await?;
    db.write(vec![
        Write::Clear { store: idb::SONGS },
        Write::Clear { store: idb::FILES },
    ])
    .await
}

/// Removes imported songs and their files.
pub(crate) async fn delete_imported(ids: &[String]) -> Result<(), String> {
    let db = Db::open().await?;
    let writes = ids
        .iter()
        .flat_map(|id| {
            [
                Write::Delete {
                    store: idb::SONGS,
                    key: id.clone(),
                },
                Write::DeletePrefix {
                    store: idb::FILES,
                    prefix: file_key(id, ""),
                },
            ]
        })
        .collect();
    db.write(writes).await
}
