//! Bundled song library: a manifest at `songs/index.json` (generated by
//! `xtask gen-songs` from `assets/songs/`) lists each song's directory, chart
//! file and audio file, all served as static assets next to the app.

use ddi_chart::Song;
use ddi_chart::formats::sm::parse_simfile;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub(crate) struct ManifestEntry {
    /// Stable id, also the directory name under `songs/`.
    pub(crate) id: String,
    pub(crate) title: String,
    pub(crate) artist: String,
    /// Chart file name inside the directory (`.sm` or `.ssc`).
    pub(crate) chart: String,
    /// Audio file name inside the directory.
    pub(crate) music: String,
    #[serde(default)]
    pub(crate) banner: Option<String>,
    #[serde(default)]
    pub(crate) background: Option<String>,
    /// Short credit line shown in the song list (full credits live in the
    /// Credits screen).
    #[serde(default)]
    pub(crate) credit: String,
    #[serde(default)]
    pub(crate) bpm: String,
    #[serde(default)]
    pub(crate) preview_start: f64,
    #[serde(default)]
    pub(crate) preview_length: f64,
    #[serde(default)]
    pub(crate) charts: Vec<ChartInfo>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub(crate) struct ChartInfo {
    pub(crate) index: usize,
    pub(crate) layout: String,
    pub(crate) difficulty: String,
    pub(crate) meter: u32,
    #[serde(default)]
    pub(crate) name: String,
    #[serde(default)]
    pub(crate) credit: String,
    #[serde(default)]
    pub(crate) notes: usize,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub(crate) struct Manifest {
    pub(crate) songs: Vec<ManifestEntry>,
}

/// A song with its chart parsed and audio bytes still encoded.
pub(crate) struct LoadedSong {
    pub(crate) entry: ManifestEntry,
    pub(crate) song: Song,
    pub(crate) music_bytes: Vec<u8>,
}

fn base_url() -> String {
    // Assets live next to index.html; the document URL (minus hash/query)
    // points at the right directory under any `--public-url`.
    let href = web_sys::window()
        .and_then(|w| w.document())
        .and_then(|d| d.base_uri().ok().flatten())
        .unwrap_or_default();
    let href = href.split('#').next().unwrap_or("");
    let href = href.split('?').next().unwrap_or("");
    match href.rfind('/') {
        Some(i) => href[..=i].to_string(),
        None => String::new(),
    }
}

pub(crate) fn asset_url(path: &str) -> String {
    format!("{}{}", base_url(), path)
}

pub(crate) async fn fetch_text(path: &str) -> Result<String, String> {
    let resp = gloo::net::http::Request::get(&asset_url(path))
        .send()
        .await
        .map_err(|e| format!("GET {path}: {e}"))?;
    if !resp.ok() {
        return Err(format!("GET {path}: HTTP {}", resp.status()));
    }
    resp.text().await.map_err(|e| format!("GET {path}: {e}"))
}

pub(crate) async fn fetch_bytes(path: &str) -> Result<Vec<u8>, String> {
    let resp = gloo::net::http::Request::get(&asset_url(path))
        .send()
        .await
        .map_err(|e| format!("GET {path}: {e}"))?;
    if !resp.ok() {
        return Err(format!("GET {path}: HTTP {}", resp.status()));
    }
    resp.binary().await.map_err(|e| format!("GET {path}: {e}"))
}

pub(crate) async fn load_manifest() -> Result<Manifest, String> {
    let text = fetch_text("songs/index.json").await?;
    serde_json::from_str(&text).map_err(|e| format!("songs/index.json: {e}"))
}

pub(crate) async fn load_song(entry: &ManifestEntry) -> Result<LoadedSong, String> {
    let chart_path = format!("songs/{}/{}", entry.id, entry.chart);
    let music_path = format!("songs/{}/{}", entry.id, entry.music);
    let (chart_text, music_bytes) =
        futures_join(fetch_text(&chart_path), fetch_bytes(&music_path)).await;
    let chart_text = chart_text?;
    let music_bytes = music_bytes?;
    let ext = entry.chart.rsplit('.').next().unwrap_or("sm");
    let song = parse_simfile(&chart_text, ext).map_err(|e| format!("{}: {e}", entry.chart))?;
    Ok(LoadedSong {
        entry: entry.clone(),
        song,
        music_bytes,
    })
}

/// Minimal join for two futures without pulling in `futures`.
async fn futures_join<A, B>(a: A, b: B) -> (A::Output, B::Output)
where
    A: std::future::Future,
    B: std::future::Future,
{
    // Sequential is fine here: both are network bound and the browser
    // pipelines them anyway once the first request is in flight.
    let ra = a.await;
    let rb = b.await;
    (ra, rb)
}
