use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use serde::Deserialize;

mod credits;
mod songs;

#[derive(Parser)]
#[command(about = "Build and maintenance tasks for the DitoDitoInfinito workspace")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Regenerate the SEO metadata fragments and sitemap from seo/metadata.toml.
    #[command(name = "regen-seo")]
    RegenSeo,
    /// Generate target/songs/index.json from assets/songs/*/ (chart + PROVENANCE.toml).
    #[command(name = "gen-songs")]
    GenSongs {
        /// Fail instead of writing when the output would change (CI check).
        #[arg(long)]
        check: bool,
    },
    /// Generate CREDITS.md and target/credits/credits.json from the song
    /// provenance records and REUSE.toml.
    #[command(name = "gen-credits")]
    GenCredits {
        /// Fail instead of writing when CREDITS.md would change (CI check).
        #[arg(long)]
        check: bool,
    },
    /// Copy the video decoder (target/video/, built by `just video`) into
    /// the site being built, when it was built. Trunk runs this after a
    /// build, with TRUNK_STAGING_DIR set.
    #[command(name = "stage-video")]
    StageVideo {
        /// The site's folder (default: $TRUNK_STAGING_DIR).
        #[arg(long)]
        dest: Option<PathBuf>,
    },
}

struct SeoPaths {
    metadata: PathBuf,
    generated_dir: PathBuf,
    head: PathBuf,
    body: PathBuf,
    sitemap: PathBuf,
}

fn seo_paths() -> SeoPaths {
    let repo_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask crate lives inside the workspace root")
        .to_path_buf();
    let generated_dir = repo_root.join("target/seo");
    SeoPaths {
        metadata: repo_root.join("seo/metadata.toml"),
        head: generated_dir.join("seo-head.html"),
        body: generated_dir.join("seo-body.html"),
        sitemap: generated_dir.join("sitemap.xml"),
        generated_dir,
    }
}

#[derive(Debug, Deserialize)]
struct SeoManifest {
    default_locale: String,
    site_name: String,
    alternate_name: Option<String>,
    theme_color_light: String,
    theme_color_dark: String,
    canonical_url: String,
    favicon_href: String,
    apple_touch_icon_href: Option<String>,
    social_image_url: Option<String>,
    social_image_alt: Option<String>,
    social_image_type: Option<String>,
    social_image_width: Option<u32>,
    social_image_height: Option<u32>,
    robots: String,
    application_category: String,
    operating_system: String,
    genres: Vec<String>,
    play_modes: Vec<String>,
    twitter_card: Option<String>,
    twitter_site: Option<String>,
    is_accessible_for_free: Option<bool>,
    offers_price: Option<String>,
    offers_price_currency: Option<String>,
    locales: BTreeMap<String, SeoLocale>,
}

#[derive(Debug, Deserialize)]
struct SeoLocale {
    lang: String,
    title: String,
    description: String,
    structured_data_description: String,
    accessible_name: String,
    accessible_summary: String,
    noscript_title: String,
    noscript: String,
    og_locale: Option<String>,
}

impl SeoManifest {
    fn default_locale_entry(&self) -> Result<(&str, &SeoLocale)> {
        let locale_key = self.default_locale.as_str();
        let locale = self
            .locales
            .get(locale_key)
            .with_context(|| format!("missing [locales.{locale_key}] entry in SEO manifest"))?;
        Ok((locale_key, locale))
    }
}

const GENERATED_BANNER: &str =
    "<!-- Generated by `cargo run -p xtask -- regen-seo`. Edit `seo/metadata.toml` instead. -->";

fn regen_seo(paths: &SeoPaths) -> Result<()> {
    fs::create_dir_all(&paths.generated_dir)
        .with_context(|| format!("failed to create {}", paths.generated_dir.display()))?;

    let manifest_text = fs::read_to_string(&paths.metadata)
        .with_context(|| format!("failed to read {}", paths.metadata.display()))?;
    let manifest: SeoManifest = toml::from_str(&manifest_text)
        .with_context(|| format!("failed to parse {}", paths.metadata.display()))?;
    let (_locale_key, locale) = manifest.default_locale_entry()?;

    fs::write(&paths.head, render_seo_head(&manifest, locale)?)
        .with_context(|| format!("failed to write {}", paths.head.display()))?;
    fs::write(&paths.body, render_seo_body(locale))
        .with_context(|| format!("failed to write {}", paths.body.display()))?;
    fs::write(&paths.sitemap, render_seo_sitemap(&manifest))
        .with_context(|| format!("failed to write {}", paths.sitemap.display()))?;
    Ok(())
}

fn icon_mime_type(href: &str) -> &'static str {
    let path = href.split(['?', '#']).next().unwrap_or(href);
    match path.rsplit('.').next() {
        Some("svg") => "image/svg+xml",
        Some("ico") => "image/x-icon",
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("gif") => "image/gif",
        Some("webp") => "image/webp",
        _ => "image/png",
    }
}

fn render_seo_head(manifest: &SeoManifest, locale: &SeoLocale) -> Result<String> {
    let mut main_entity = serde_json::json!({
        "@type": "VideoGame",
        "name": &manifest.site_name,
        "url": &manifest.canonical_url,
        "description": &locale.structured_data_description,
        "genre": &manifest.genres,
        "applicationCategory": &manifest.application_category,
        "operatingSystem": &manifest.operating_system,
    });
    if let Some(image) = &manifest.social_image_url {
        main_entity["image"] = serde_json::json!(image);
    }
    if let Some(alternate_name) = &manifest.alternate_name {
        main_entity["alternateName"] = serde_json::json!(alternate_name);
    }
    if !manifest.play_modes.is_empty() {
        main_entity["playMode"] = serde_json::json!(&manifest.play_modes);
    }
    if let Some(free) = manifest.is_accessible_for_free {
        main_entity["isAccessibleForFree"] = serde_json::json!(free);
    }
    if let Some(price) = &manifest.offers_price {
        let mut offer = serde_json::json!({
            "@type": "Offer",
            "price": price,
        });
        if let Some(currency) = &manifest.offers_price_currency {
            offer["priceCurrency"] = serde_json::json!(currency);
        }
        main_entity["offers"] = offer;
    }
    let mut web_page = serde_json::json!({
        "@context": "https://schema.org",
        "@type": "WebPage",
        "name": &manifest.site_name,
        "url": &manifest.canonical_url,
        "description": &locale.description,
        "inLanguage": &locale.lang,
    });
    if let Some(image) = &manifest.social_image_url {
        web_page["image"] = serde_json::json!(image);
    }
    web_page["mainEntity"] = main_entity;
    let structured_data = serde_json::to_string_pretty(&web_page)?;

    let mut html = String::new();
    writeln!(html, "{GENERATED_BANNER}")?;
    writeln!(html, "<title>{}</title>", escape_html_text(&locale.title))?;
    writeln!(
        html,
        r#"<meta name="description" content="{}"/>"#,
        escape_html_attr(&locale.description)
    )?;
    writeln!(
        html,
        r#"<meta name="robots" content="{}"/>"#,
        escape_html_attr(&manifest.robots)
    )?;
    writeln!(
        html,
        r#"<meta name="theme-color" content="{}" media="(prefers-color-scheme: light)"/>"#,
        escape_html_attr(&manifest.theme_color_light)
    )?;
    writeln!(
        html,
        r#"<meta name="theme-color" content="{}" media="(prefers-color-scheme: dark)"/>"#,
        escape_html_attr(&manifest.theme_color_dark)
    )?;
    writeln!(
        html,
        r#"<link rel="canonical" href="{}"/>"#,
        escape_html_attr(&manifest.canonical_url)
    )?;
    writeln!(
        html,
        r#"<link rel="icon" type="{}" href="{}"/>"#,
        icon_mime_type(&manifest.favicon_href),
        escape_html_attr(&manifest.favicon_href)
    )?;
    if let Some(apple_touch_icon) = &manifest.apple_touch_icon_href {
        writeln!(
            html,
            r#"<link rel="apple-touch-icon" href="{}"/>"#,
            escape_html_attr(apple_touch_icon)
        )?;
    }
    writeln!(html, r#"<meta property="og:type" content="website"/>"#)?;
    if let Some(og_locale) = &locale.og_locale {
        writeln!(
            html,
            r#"<meta property="og:locale" content="{}"/>"#,
            escape_html_attr(og_locale)
        )?;
    }
    writeln!(
        html,
        r#"<meta property="og:site_name" content="{}"/>"#,
        escape_html_attr(&manifest.site_name)
    )?;
    writeln!(
        html,
        r#"<meta property="og:title" content="{}"/>"#,
        escape_html_attr(&locale.title)
    )?;
    writeln!(
        html,
        r#"<meta property="og:description" content="{}"/>"#,
        escape_html_attr(&locale.description)
    )?;
    writeln!(
        html,
        r#"<meta property="og:url" content="{}"/>"#,
        escape_html_attr(&manifest.canonical_url)
    )?;
    if let Some(social_image_url) = &manifest.social_image_url {
        writeln!(
            html,
            r#"<meta property="og:image" content="{}"/>"#,
            escape_html_attr(social_image_url)
        )?;
        if let Some(social_image_alt) = &manifest.social_image_alt {
            writeln!(
                html,
                r#"<meta property="og:image:alt" content="{}"/>"#,
                escape_html_attr(social_image_alt)
            )?;
        }
        if let Some(social_image_type) = &manifest.social_image_type {
            writeln!(
                html,
                r#"<meta property="og:image:type" content="{}"/>"#,
                escape_html_attr(social_image_type)
            )?;
        }
        if let Some(social_image_width) = manifest.social_image_width {
            writeln!(
                html,
                r#"<meta property="og:image:width" content="{social_image_width}"/>"#
            )?;
        }
        if let Some(social_image_height) = manifest.social_image_height {
            writeln!(
                html,
                r#"<meta property="og:image:height" content="{social_image_height}"/>"#
            )?;
        }
    }
    if let Some(twitter_card) = &manifest.twitter_card {
        writeln!(
            html,
            r#"<meta name="twitter:card" content="{}"/>"#,
            escape_html_attr(twitter_card)
        )?;
        if let Some(twitter_site) = &manifest.twitter_site {
            writeln!(
                html,
                r#"<meta name="twitter:site" content="{}"/>"#,
                escape_html_attr(twitter_site)
            )?;
        }
        writeln!(
            html,
            r#"<meta name="twitter:title" content="{}"/>"#,
            escape_html_attr(&locale.title)
        )?;
        writeln!(
            html,
            r#"<meta name="twitter:description" content="{}"/>"#,
            escape_html_attr(&locale.description)
        )?;
        if let Some(social_image_url) = &manifest.social_image_url {
            writeln!(
                html,
                r#"<meta name="twitter:image" content="{}"/>"#,
                escape_html_attr(social_image_url)
            )?;
            if let Some(social_image_alt) = &manifest.social_image_alt {
                writeln!(
                    html,
                    r#"<meta name="twitter:image:alt" content="{}"/>"#,
                    escape_html_attr(social_image_alt)
                )?;
            }
        }
    }
    writeln!(html, r#"<script type="application/ld+json">"#)?;
    writeln!(html, "{structured_data}")?;
    writeln!(html, "</script>")?;
    Ok(html)
}

fn render_seo_body(locale: &SeoLocale) -> String {
    format!(
        concat!(
            "{banner}\n",
            "<h1 class=\"sr-only\">{name}</h1>\n",
            "<p class=\"sr-only\">{summary}</p>\n",
            "<noscript>\n",
            "  <div class=\"boot-noscript\" role=\"alert\">\n",
            "    <div class=\"boot-noscript-title\">{noscript_title}</div>\n",
            "    <div class=\"boot-noscript-message\">{noscript}</div>\n",
            "  </div>\n",
            "</noscript>\n"
        ),
        banner = GENERATED_BANNER,
        name = escape_html_text(&locale.accessible_name),
        summary = escape_html_text(&locale.accessible_summary),
        noscript_title = escape_html_text(&locale.noscript_title),
        noscript = escape_html_text(&locale.noscript),
    )
}

fn render_seo_sitemap(manifest: &SeoManifest) -> String {
    format!(
        concat!(
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n",
            "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n",
            "  <url>\n",
            "    <loc>{}</loc>\n",
            "  </url>\n",
            "</urlset>\n"
        ),
        escape_html_text(&manifest.canonical_url)
    )
}

fn escape_html_text(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '&' => escaped.push_str("&amp;"),
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            _ => escaped.push(ch),
        }
    }
    escaped
}

fn escape_html_attr(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '&' => escaped.push_str("&amp;"),
            '"' => escaped.push_str("&quot;"),
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            _ => escaped.push(ch),
        }
    }
    escaped
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Commands::RegenSeo => regen_seo(&seo_paths()),
        Commands::GenSongs { check } => songs::gen_songs(check),
        Commands::GenCredits { check } => credits::gen_credits(check),
        Commands::StageVideo { dest } => stage_video(dest),
    }
}

/// The module, its description and its licence, served from `video/`.
const VIDEO_FILES: [&str; 3] = ["ddivideo.wasm", "ddivideo.json", "ddivideo.LICENSE.txt"];

fn stage_video(dest: Option<PathBuf>) -> Result<()> {
    let dest = match dest {
        Some(d) => d,
        None => PathBuf::from(
            std::env::var_os("TRUNK_STAGING_DIR")
                .context("stage-video needs --dest or TRUNK_STAGING_DIR")?,
        ),
    };
    let built = Path::new(env!("CARGO_MANIFEST_DIR")).join("../target/video");
    if !built.join(VIDEO_FILES[0]).exists() {
        // The app works without it: movies only the module decodes show
        // the song background instead.
        eprintln!(
            "stage-video: no video decoder in target/video (run `just video`); building without it"
        );
        return Ok(());
    }
    let out = dest.join("video");
    fs::create_dir_all(&out).with_context(|| format!("creating {}", out.display()))?;
    for name in VIDEO_FILES {
        let from = built.join(name);
        fs::copy(&from, out.join(name)).with_context(|| format!("copying {}", from.display()))?;
    }
    eprintln!("stage-video: video decoder copied to {}", out.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_manifest() -> SeoManifest {
        let mut locales = BTreeMap::new();
        locales.insert(
            "en".to_string(),
            SeoLocale {
                lang: "en".to_string(),
                title: "Title & Co".to_string(),
                description: "A \"quoted\" description".to_string(),
                structured_data_description: "Structured description".to_string(),
                accessible_name: "Name <b>".to_string(),
                accessible_summary: "Summary".to_string(),
                noscript_title: "JavaScript is required.".to_string(),
                noscript: "Enable JavaScript.".to_string(),
                og_locale: Some("en_US".to_string()),
            },
        );
        SeoManifest {
            default_locale: "en".to_string(),
            site_name: "Dito Dito Infinito (Demo)".to_string(),
            alternate_name: None,
            theme_color_light: "#ffffff".to_string(),
            theme_color_dark: "#161318".to_string(),
            canonical_url: "https://example.test/app/".to_string(),
            favicon_href: "img/favicon.png".to_string(),
            apple_touch_icon_href: Some("img/favicon.png".to_string()),
            social_image_url: Some("https://example.test/app/img/og.png".to_string()),
            social_image_alt: Some("Alt text".to_string()),
            social_image_type: Some("image/png".to_string()),
            social_image_width: Some(1080),
            social_image_height: Some(1628),
            robots: "index,follow".to_string(),
            application_category: "GameApplication".to_string(),
            operating_system: "Web browser".to_string(),
            genres: vec!["Hidden object".to_string()],
            play_modes: vec!["SinglePlayer".to_string()],
            twitter_card: Some("summary".to_string()),
            twitter_site: None,
            is_accessible_for_free: Some(true),
            offers_price: None,
            offers_price_currency: None,
            locales,
        }
    }

    #[test]
    fn head_contains_dual_theme_colors_and_png_favicon() {
        let manifest = test_manifest();
        let (_, locale) = manifest.default_locale_entry().unwrap();
        let head = render_seo_head(&manifest, locale).unwrap();
        assert!(head.contains(r#"media="(prefers-color-scheme: light)""#));
        assert!(head.contains(r#"media="(prefers-color-scheme: dark)""#));
        assert!(head.contains(r#"<link rel="icon" type="image/png" href="img/favicon.png"/>"#));
        assert!(head.contains(r#"<link rel="apple-touch-icon" href="img/favicon.png"/>"#));
    }

    #[test]
    fn icon_mime_type_is_inferred_from_extension() {
        assert_eq!(icon_mime_type("img/favicon.png"), "image/png");
        assert_eq!(icon_mime_type("favicon.svg"), "image/svg+xml");
        assert_eq!(icon_mime_type("favicon.ico"), "image/x-icon");
        assert_eq!(icon_mime_type("favicon.png?v=2"), "image/png");
    }

    #[test]
    fn head_escapes_html_in_text_and_attributes() {
        let manifest = test_manifest();
        let (_, locale) = manifest.default_locale_entry().unwrap();
        let head = render_seo_head(&manifest, locale).unwrap();
        assert!(head.contains("<title>Title &amp; Co</title>"));
        assert!(head.contains(r#"content="A &quot;quoted&quot; description""#));
    }

    #[test]
    fn head_structured_data_has_video_game_entity() {
        let manifest = test_manifest();
        let (_, locale) = manifest.default_locale_entry().unwrap();
        let head = render_seo_head(&manifest, locale).unwrap();
        assert!(head.contains(r#""@type": "VideoGame""#));
        assert!(head.contains(r#""playMode""#));
        assert!(head.contains(r#""SinglePlayer""#));
        assert!(head.contains(r#""isAccessibleForFree": true"#));
    }

    #[test]
    fn head_omits_optional_tags_when_unset() {
        let mut manifest = test_manifest();
        manifest.twitter_card = None;
        manifest.apple_touch_icon_href = None;
        manifest.alternate_name = None;
        manifest.play_modes.clear();
        let (_, locale) = manifest.default_locale_entry().unwrap();
        let head = render_seo_head(&manifest, locale).unwrap();
        assert!(!head.contains("twitter:"));
        assert!(!head.contains("apple-touch-icon"));
        assert!(!head.contains("alternateName"));
        assert!(!head.contains("playMode"));
    }

    #[test]
    fn head_omits_all_image_tags_without_social_image() {
        let mut manifest = test_manifest();
        manifest.social_image_url = None;
        manifest.social_image_alt = None;
        manifest.social_image_type = None;
        manifest.social_image_width = None;
        manifest.social_image_height = None;
        let (_, locale) = manifest.default_locale_entry().unwrap();
        let head = render_seo_head(&manifest, locale).unwrap();
        assert!(!head.contains("og:image"));
        assert!(!head.contains("twitter:image"));
        assert!(!head.contains(r#""image""#));
        // The twitter card itself survives without an image.
        assert!(head.contains(r#"<meta name="twitter:card" content="summary"/>"#));
    }

    #[test]
    fn body_uses_sr_only_and_boot_noscript_markup() {
        let manifest = test_manifest();
        let (_, locale) = manifest.default_locale_entry().unwrap();
        let body = render_seo_body(locale);
        assert!(body.contains(r#"<h1 class="sr-only">Name &lt;b&gt;</h1>"#));
        assert!(body.contains(r#"<div class="boot-noscript" role="alert">"#));
        assert!(body.contains(r#"<div class="boot-noscript-title">JavaScript is required.</div>"#));
        assert!(body.contains(r#"<div class="boot-noscript-message">Enable JavaScript.</div>"#));
    }

    #[test]
    fn sitemap_contains_canonical_url() {
        let manifest = test_manifest();
        let sitemap = render_seo_sitemap(&manifest);
        assert!(sitemap.contains("<loc>https://example.test/app/</loc>"));
    }

    #[test]
    fn real_manifest_parses_and_renders() {
        let paths = seo_paths();
        let manifest_text = fs::read_to_string(&paths.metadata).unwrap();
        let manifest: SeoManifest = toml::from_str(&manifest_text).unwrap();
        let (_, locale) = manifest.default_locale_entry().unwrap();
        let head = render_seo_head(&manifest, locale).unwrap();
        assert!(head.contains("<title>"));
        assert!(head.contains("Dito Dito Infinito"));
    }
}
